import type { Node, Edge } from "@xyflow/react";
import { generatePythonCode, makeTimestampSuffix } from "./graphExecution";

// --- minimal Jupyter cell helpers (kept local so this util is self-contained) ---
const notebookSource = (text: string): string[] => {
  const lines = text.replace(/\r\n/g, "\n").split("\n");
  return lines.map((line, idx) => (idx < lines.length - 1 ? `${line}\n` : line));
};
const markdownCell = (text: string) => ({ cell_type: "markdown", metadata: {}, source: notebookSource(text) });
const codeCell = (text: string) => ({
  cell_type: "code",
  execution_count: null,
  metadata: {},
  outputs: [],
  source: notebookSource(text),
});
const stripOperationMarkers = (pythonCode: string): string =>
  pythonCode
    .replace(/\r\n/g, "\n")
    .split("\n")
    .filter((line) => !line.trim().startsWith("# --- Operation:"))
    .join("\n");

/** True when the graph has a Simulate node using the GROMACS engine — the only case
 *  where the GPU-Colab notebook (CUDA gmx) is relevant. */
export const hasGromacsSimulateNode = (nodes: Node[]): boolean =>
  nodes.some(
    (n) => n.type === "simulate" && (n.data as Record<string, unknown> | undefined)?.engine === "gromacs",
  );

/**
 * Self-contained Google Colab notebook that runs the GROMACS workflow on a GPU.
 * GROMACS is local-only on the server (no GPU on Cloud Run); this notebook installs a
 * CUDA-enabled GROMACS from conda-forge so the user can run grompp/mdrun on a Colab T4.
 * The generated build script is reused verbatim except the gmx path is forced to 'gmx'
 * (the conda binary on PATH) instead of the node's local install path.
 */
export const buildGromacsColabNotebook = (nodes: Node[], edges: Edge[]): string => {
  let script = stripOperationMarkers(generatePythonCode(nodes, edges, "strict"));
  // Colab uses the conda-forge gmx on PATH, not a local GMXRC/install path.
  script = script.replace(/_gmx_spec\s*=\s*'[^']*'/g, "_gmx_spec = 'gmx'");
  // Drop the SSE-protocol marker prints (__VISUALIZE__/__PLOT__/__CHARGES__/…) — they
  // are only meaningful to the web UI and would dump huge strings into the Colab output.
  script = script
    .split("\n")
    .filter((l) => !/\bprint\(\s*f?["']__[A-Z]/.test(l))
    .join("\n");

  const cells: Array<Record<string, unknown>> = [];
  cells.push(markdownCell([
    "# GROMACS on Google Colab (GPU)",
    "",
    "Generated by the atomipy web module.",
    "",
    "**First:** *Runtime → Change runtime type → Hardware accelerator = **GPU (T4)**.*",
    "",
    "**How to run:**",
    "1. Run **Cell 1** (installs conda). The kernel **restarts automatically** — that is expected.",
    "2. After the restart, run the remaining cells top to bottom (*Runtime → Run all* also works — it resumes after the restart).",
    "",
    "GROMACS auto-offloads the nonbonded/PME work to the GPU when the CUDA build is installed.",
  ].join("\n")));

  cells.push(markdownCell("## Cell 1 — install conda (restarts the kernel)"));
  cells.push(codeCell([
    "# Installs mambaforge and RESTARTS the kernel. Run this first, then continue below.",
    "!pip install -q condacolab",
    "import condacolab",
    "condacolab.install()",
  ].join("\n")));

  cells.push(markdownCell("## Cell 2 — install CUDA GROMACS + atomipy *(run after the restart)*"));
  cells.push(codeCell([
    "# CUDA-enabled GROMACS from conda-forge (falls back to a plain build if the cuda",
    "# selector is unavailable on this Colab image). Takes a few minutes.",
    "!mamba install -y -q -c conda-forge 'gromacs=*=nompi*cuda*' || mamba install -y -q -c conda-forge gromacs",
    "!pip install -q git+https://github.com/mholmboe/atomipy.git",
    "import subprocess, os, atomipy",
    "print(subprocess.run(['bash', '-lc', 'gmx --version | head -n 20'], capture_output=True, text=True).stdout)",
    "_gpu = subprocess.run(['bash', '-lc', 'nvidia-smi -L'], capture_output=True, text=True).stdout",
    "print(_gpu or 'WARNING: no GPU detected -- set Runtime type to GPU and rerun.')",
    "# Make bundled mineral presets available as ./UC_conf (needed for preset structures).",
    "_uc = os.path.join(os.path.dirname(atomipy.__file__), 'structures', 'minerals', 'UC_conf')",
    "if os.path.isdir(_uc) and not os.path.exists('UC_conf'):",
    "    os.symlink(_uc, 'UC_conf')",
  ].join("\n")));

  cells.push(markdownCell("## Cell 3 — build the system and run the GROMACS simulation"));
  cells.push(codeCell(script.trimEnd() + "\n"));

  cells.push(markdownCell("## Cell 4 — download the results"));
  cells.push(codeCell([
    "import glob, zipfile",
    "from google.colab import files",
    "_exts = ('gro', 'pdb', 'xtc', 'trr', 'edr', 'top', 'itp', 'log', 'mdp', 'tpr', 'dat', 'json', 'xvg')",
    "_out = [f for f in glob.glob('*') if os.path.isfile(f) and f.rsplit('.', 1)[-1] in _exts]",
    "with zipfile.ZipFile('gromacs_results.zip', 'w', zipfile.ZIP_DEFLATED) as _z:",
    "    for _f in _out:",
    "        _z.write(_f)",
    "print('Bundled', len(_out), 'files into gromacs_results.zip')",
    "files.download('gromacs_results.zip')",
  ].join("\n")));

  return JSON.stringify(
    {
      cells,
      metadata: {
        kernelspec: { display_name: "Python 3", language: "python", name: "python3" },
        accelerator: "GPU",
        colab: { provenance: [], gpuType: "T4" },
      },
      nbformat: 4,
      nbformat_minor: 5,
    },
    null,
    2,
  );
};

/** Generate + trigger a browser download of the GROMACS GPU-Colab notebook. Returns the filename. */
export const downloadGromacsColabNotebook = (nodes: Node[], edges: Edge[]): string => {
  const nb = buildGromacsColabNotebook(nodes, edges);
  const blob = new Blob([nb], { type: "application/x-ipynb+json" });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  const name = `gromacs_gpu_colab_${makeTimestampSuffix()}.ipynb`;
  link.href = url;
  link.download = name;
  link.click();
  window.URL.revokeObjectURL(url);
  return name;
};
