"""Provenance string for files written by atomipy exporters."""
from datetime import datetime


def provenance_string():
    """Return e.g. 'Generated by atomipy 0.96 on 2026-06-06'.

    The version is imported lazily to avoid a circular import: this module
    is imported by the writer modules, which are imported by the package
    __init__ before __version__ is necessarily defined at import time.
    """
    try:
        from . import __version__ as _v
    except Exception:  # pragma: no cover
        _v = "unknown"
    return f"Generated by atomipy {_v} on {datetime.now():%Y-%m-%d}"
